### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by riddhibanerjee** [spectralDNS/spectralDNS#19]
Hi, I just started using your code because it's written in python and I love python. I used to use the code Tarang when I was in Prof. Verma's lab but it was in C++. I just cloned the repository and ran the command 'python setup.py install --prefix=...' in the terminal. After this when I am trying to run the file TG.py in the folder demo, using the command 'mpirun -np 2 python TG.py' it shows me the error: Traceback (most recent call last):
  File "TG.py", line 1, in <module>
    from spectralDNS import config, get_solver, solve
ImportError: No module named spectralDNS

I shall be glad if you could help me with this.

Thanks.

Regards,
Riddhi Bandyopadhyay.
Graduate student,
University of Delaware.

**Comment by mikaem** [comment]
Hi Riddhi

The ... is placeholder for a directory that is on the PYTHONPATH. You can skip the prefix and then the program will be installed into /usr/local/lib/python2.7/site-packages (I think?), but then you need to do sudo python setup.py install. Regular distutils installation.

Hope you can make it work:-)

Regards

Mikael

**Comment by riddhibanerjee** [comment]
Hi Mikael,

Thank for the clarification. I could get rid of the error. But now when I try to run the file it shows this error.

usage: TG.py [-h] [--precision {single,double}]
             [--optimization {cython,weave,numba}]
             [--make_profile MAKE_PROFILE] [--dt DT] [--T T]
             [--write_result tstep] [--checkpoint CHECKPOINT] [--nu NU]
             [--t T] [--tstep TSTEP] [--dealias {2/3-rule,3/2-rule,None}]
             [--ntol NTOL] [--threads THREADS]
             [--planner_effort PLANNER_EFFORT] [--h5filename H5FILENAME]
             [--convection {Standard,Divergence,Skewed,Vortex}]
             [--communication {Alltoallw,alltoall,Sendrecv_replace,Swap,Nyquist}]
             [--L Lx Ly Lz] [--Pencil_alignment {X,Y}] [--Pencil_P1 PENCIL_P1]
             [--decomposition {slab,pencil}] [--M Mx My Mz]
             [--write_yz_slice i tstep] [--write_xz_slice j tstep]
             [--write_xy_slice k tstep] [--TOL TOL]
             [--integrator {RK4,ForwardEuler,AB2,BS5_adaptive,BS5_fixed}]
             [--compute_energy COMPUTE_ENERGY] [--plot_step PLOT_STEP]
             {NS,VV,MHD} ...
TG.py: error: too few arguments
An exception has occurred, use %tb to see the full traceback.

Can you please explain why this is happening?

Regards,
Riddhi.

**Comment by mikaem** [comment]
Try mpirun -np 2 python TG.py NS
This chooses the regular Navier Stokes solver. Use VV for a velocity vorticity formulation.
