### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by mschneier91** [spectralDNS/spectralDNS#31]
Hello,

I'm have an issue with installation via conda. After cloinng and using 

conda build -c conda-forge conf/conda

I'm getting that the build fails. I get the following results for the build tests

test_MHD.py::test_MHD[uniform] FAILED                                    [  5%]
test_MHD.py::test_MHD[nonuniform] FAILED                                 [ 11%]
test_NS2D.py::test_NS2D[1] FAILED                                        [ 16%]
test_NS2D.py::test_NS2D[2] FAILED                                        [ 22%]
test_NSVV.py::test_solvers[NS/uniform] FAILED                            [ 27%]
test_NSVV.py::test_solvers[VV/uniform] FAILED                            [ 33%]
test_NSVV.py::test_solvers[NS/nonuniform] FAILED                         [ 38%]
test_NSVV.py::test_solvers[VV/nonuniform] FAILED                         [ 44%]
test_NSVV.py::test_integrators[NS/uniform] FAILED                        [ 50%]
test_NSVV.py::test_integrators[VV/uniform] FAILED                        [ 55%]
test_NSVV.py::test_integrators[NS/nonuniform] FAILED                     [ 61%]
test_NSVV.py::test_integrators[VV/nonuniform] FAILED                     [ 66%]
test_channel.py::test_channel[KMMRK3] FAILED                             [ 72%]
test_channel.py::test_channel[KMM] PASSED                                [ 77%]
test_channelz.py::test_channel[KMMr] PASSED                              [ 83%]
test_shentransforms.py::test_Mult_Div PASSED                             [ 88%]
test_shentransforms.py::test_Mult_CTD_3D[GC] PASSED                      [ 94%]
test_shentransforms.py::test_Mult_CTD_3D[GL] PASSED                      [100%]

The specific issue seems to be in all the test failures.

AttributeError: 'TensorProductSpace' object has no attribute 'local_shape'

Thank you for any assistance you can provide.

**Comment by mikaem** [comment]
Thanks for the bug report, it's an incompatibility issue with the latest version of shenfun. I've pushed a fix to master and it should now be ok.

**Comment by mschneier91** [comment]
Thank you the installation worked, everything seems to be working now.
