### ISSUE TITLE
Imaginary frequencies possibly due to aliasing Nyquist Frequency

### ISSUE THREAD

**Issue by natschil** [spectralDNS/spectralDNS#32]
Energy calculated in frequency space is different to that calculated in physical space. This suggests there is an incorrect imaginary component. 

 To see this, take the master branch of spectralDNS and look at demo/TG.py, with nu=1./280 and dt=0.1 on a 64^3 grid, and compare energy in frequency and physical space, they will diverge quite quickly.

**Comment by natschil** [comment]
Here is a minimal example that shoes the issue with the Taylor-Green vortex as discussed above: https://gist.github.com/natschil/5a935ab4dab40b29c2045782b5beda3b

**Comment by mikaem** [comment]
This should now be fixed by masking the Nyquist frequency of the nonlinear convection term.
