### ISSUE TITLE
HDF5 data in TG.py

### ISSUE THREAD

**Issue by Daniel-J123** [spectralDNS/spectralDNS#37]
hi mikaem
After I have ran TG.py in  `Demo` , I use fortran to  read the output file NS9_w.h5 data ,but here no definition of the HDF5 group, dataset in the TG.py code. However , when I read data from Isotraopic.py's result, I found something like this :
`context.spectrumname = context.hdf5file.filename+".h5"
    
f = h5py.File(context.spectrumname, mode='w', driver='mpio', comm=sol.comm)
    
f.create_group("Turbulence")
   
f["Turbulence"].create_group("Ek")
   
bins = np.array(bins)
  
 f["Turbulence"].create_dataset("bins", data=bins)  `
![图片](https://user-images.githubusercontent.com/66522801/89630234-a5d22a80-d8d1-11ea-86fb-8c839444c5a2.png)

So, I want to ask you in TG.py code, what's the HDF5 data structure? About the file , dataset, dataspace so on....

thank you for your work and reply!

**Comment by Daniel-J123** [comment]
hello hello hello professor mikaem ,are you see my question? I am sorry to need your help! thank you

**Comment by mikaem** [comment]
Hi Daniel,

Please look up a manual on HDF5 or h5py.

**Comment by Daniel-J123** [comment]
yeah I solved it!
the last generated NS9_w.h5 is a final file which concludes lots of timesteps,  but how to get every timestep results h5 files?
