### ISSUE TITLE
ImportError: cannot import name 'VectorTensorProductSpace' from 'shenfun' 

### ISSUE THREAD

**Issue by Daniel-J123** [spectralDNS/spectralDNS#38]
hi mikaem
recently ,my computer had faced some problems, and I restart install the spectralDNS in linux system followed by your method on github, and everything looks great,
but when I do this on the terminal like: python TG.py NS
there is a issue appears 
![图片](https://user-images.githubusercontent.com/66522801/93412977-d2b22e00-f8d0-11ea-93b4-54d7eea860cc.png)

and now I feel very anxious, please help me again！

**Comment by Daniel-J123** [comment]
please please!please! I feel so anxious to need your suggestion! mikaem

**Comment by mikaem** [comment]
See https://github.com/spectralDNS/shenfun/releases/tag/3.0.6
You can still use version 3.0.5 of shenfun, or modify your code accordingly.

**Comment by Daniel-J123** [comment]
oh sorry mikaem, I know your what said, but:
I used the method you gave on GitHub to install the spectralDNS virtual environment, and use conda list to view the packages in the environment. This is the version of shenfun, which has been automatically downloaded as shenfun 3.0.6, but run `python TG.py NS` Still have the same problem!

**Comment by Daniel-J123** [comment]
I remember that when it was available before, shenfun was version 3.0.5, but now when spectralDNS is installed, shenfun is automatically downloaded as 3.0.6, so there is a problem, I want to reduce shenfun 3.0.6 version to 3.0.5, but I can't succeed.
So i don't know where the error is！

**Comment by mikaem** [comment]
It should work now. For future reference, if you want to install shenfun 3.0.5, simply do

    conda install shenfun=3.0.5

**Comment by Daniel-J123** [comment]
this is my `conda list` results:
![图片](https://user-images.githubusercontent.com/66522801/93442426-97c8ee00-f902-11ea-9fcd-55973ffe162b.png)
here shenfun=3.0.6
 and I use `conda install shenfun=3.0.5` ,but the error occurs
![图片](https://user-images.githubusercontent.com/66522801/93443211-d068c780-f902-11ea-8618-c86a2c02cc12.png)

so i also use `anaconda search -t conda shenfun` to search shenfun's version and found that:
![图片](https://user-images.githubusercontent.com/66522801/93444435-289fc980-f903-11ea-9405-e18a7a07c15c.png)
 there are just two shenfun packages and both version 3.0.6 ,not 3.0.5

what's wrong? bug?

**Comment by mikaem** [comment]
There's no bug. You probably do not have conda-forge in your default channels. Try

    conda install -c conda-forge shenfun=3.0.5

**Comment by Daniel-J123** [comment]
on yeah I know your means!!
I modify the code in NS solver `VectorTensorProductSpace to VectorSpace`, and the `python TG.py NS` works!!
yes! you release the latest shenfun=3.0.6 yesterday, and now if someone install the spectralDNS ,shenfun=3.0.6,but we should modify the code(some module name)[https://github.com/spectralDNS/shenfun/releases/tag/3.0.6](url)

and another method is `conda install -c conda-forge shenfun=3.0.5` ，In order to match the module name in the original code！！

thank you mikaem,your work is so great！！

**Comment by Daniel-J123** [comment]
I add `from .cython_double_mpi import *`in cython_double.py and `from .cython_single_mpi import *` in cython_single.py
![图片](https://user-images.githubusercontent.com/66522801/93452458-07db7200-f90b-11ea-9b6e-3bed048f37de.png)
![图片](https://user-images.githubusercontent.com/66522801/93452681-46712c80-f90b-11ea-93a9-471ecb024be3.png)

but looks no use to solve `cross1 not optimized
cross2 not optimized
RK4 not optimized
ForwardEuler not optimized
AB2 not optimized
`
![图片](https://user-images.githubusercontent.com/66522801/93452260-cb0f7b00-f90a-11ea-98ff-ae8c7e676c50.png)

and this version seems no useful when use `mpirun -np 8 python TG.py --optimization cython NS`
![图片](https://user-images.githubusercontent.com/66522801/93453045-c0a1b100-f90b-11ea-9914-119fb5ad6bf6.png)

what's wrong?? mikaem

**Comment by Daniel-J123** [comment]
hello hello mikaem, did you see my seek help information？？？
now I don't know why exist mpi problems, can you give me some great suggestions?
Thank you 
best regards!

**Comment by mikaem** [comment]
Hi Daniel,

Looks like a problem with your installation, but it's very difficult for me to help except to point at the build instructions. I cannot tell from the error message what is wrong. Does any mpi program work or is it just spectraldns? Did you install using 

    python setup.py build_ext -i

and add the current path to the pythonpath? That it does not work in serial with optimization tells me that you have done something wrong with the installation, or not run the above command to compile the cython files?

**Comment by Daniel-J123** [comment]
hi mikaem
this is my installation step, you can look :
1. `conda create --name spectralDNS -c conda-forge shenfun mpi4py-fft cython numba pythran mpich pip h5py=*=mpi*`
2. `git clonehttps://github.com/spectralDNS/spectralDNS.git`
3. `cd spectralDNS`
4. `python setup.py build_ext -i`
and then here occurs something like this :
![图片](https://user-images.githubusercontent.com/66522801/93656941-e391a980-fa60-11ea-9b40-0b24a6fab2ab.png)

I wonder if this phenomenon is normal?
5. add the `export PYTHONPATH=/home/tao/spectralDNS/:$PYTHONPATH` to file named `.bashrc`
6. `source ~/.bashrc`
7. about optimization, I just add `from .cython_double_mpi import *`to file named **cython_double.py** and `from .cython_single_mpi import *` to named **cython_single.py** in this path **/home/tao/spectralDNS/spectralDNS/optimization**
8. `cd demo` and `conda activate spectralDNS` and then run this code `mpirun -np 8 python TG.py --optimization cython NS`

above all my step operators about installation ,but now occurs the issue for "MPI" and not  optimized
so after you look my step ,can  you find where and what my mistake in the installation ?

**Comment by Daniel-J123** [comment]
hi mikaem  
can you see my installation steps? maybe you can find my fault in that, can you tell me ? thanks!

**Comment by mikaem** [comment]
Yes, you can see from your screenshot that it is not building, because it's already built. Try

    python setup.py build_ext -if

To force a rebuild.

**Comment by Daniel-J123** [comment]
![图片](https://user-images.githubusercontent.com/66522801/93662711-d42c5380-fa94-11ea-9cac-40f5990d0f69.png)
![图片](https://user-images.githubusercontent.com/66522801/93662760-0ccc2d00-fa95-11ea-8ffa-5fa51a93f991.png)
like this screenshot, but seems no use!
 should I restart install it?? the MPI and optimization are not be solved

**Comment by Daniel-J123** [comment]
I don't know why exist `Disabling Pythran support, package not available `, is this express what?

**Comment by Daniel-J123** [comment]
hi mikaem,
I have been troubled by this MPI parallel problem for the past two days, and it has not been solved yet, and I am about to collapse. Please help me to point me to the maze again, where am I going wrong? Do I need to completely reload this virtual environment spectralDNS？？
