### ISSUE TITLE
issues about generate_xdmf to visulize

### ISSUE THREAD

**Issue by Daniel-J123** [spectralDNS/spectralDNS#39]
hi mikaem,
![image](https://user-images.githubusercontent.com/66522801/94091453-d999ed00-fe4a-11ea-8fd2-bafd02d0ad21.png)
why I use this code to visualization was useless?
`from mpi4py_fft import generate_xdmf`
  ` if sol.rank == 0:`
        `generate_xdmf(context.hdf5file.filename+"_w.h5")`
there no xdmf file generated!

**Comment by mikaem** [comment]
There is simply no xdmf file generated when there are no data. Use the 'write_result' parameter.
