### ISSUE TITLE
how to restart the program to continue the previous calculation？

### ISSUE THREAD

**Issue by Daniel-J123** [spectralDNS/spectralDNS#40]
hi，mikaem
Now I have a problem. If I am calculating the `TG.py` code,  when I calculate the time step of 10000, it is interrupted unexpectedly, then how should I restart the calculation from the result of the 10000 step? Is it necessary to start the calculation from the initial flow field? Is there a third-party interface or the like that can solve this problem?

Thank you for your reply and suggestions！

**Comment by mikaem** [comment]
The 'checkpoint' parameter is used for restarting a simulation. It stores velocity and pressure data every 'checkpoint' timestep.

**Comment by Daniel-J123** [comment]
I use the command `mpirun -np 16 python TG.py --checkpoint 10 NS`, is that means every 10 timestep to store the data? I found the NS9_c.h5 file stores something, and the data is spectral space, but When I intentionally interrupted the running program and ran the same command again, I found that instead of proceeding with the interrupted state, it started calculating again from the initial field!
mikaem, Did I do something wrong there?

**Comment by Daniel-J123** [comment]
hi mikaem
I did wrong something with restarting a simulation, I want to know after I saved the checkpoint data, if i  want to restart a simulation,  should I add the checkpoint data to where? and how realise it？ just like add initialize condition to the flowfiled??

thank you for your help!!please please please!!

**Comment by Daniel-J123** [comment]
hi professor mikaem,
do you see my ask for help?
I really try many methods to restart a simulation, but failed!
you said use the checkpoint data to solve it last time, and I was also failed till now!
please tell how to use checkpoint to restart a simulation ,ok?

**Comment by mikaem** [comment]
See [the channel flow solver](https://github.com/spectralDNS/spectralDNS/blob/master/demo/MKM.py)

**Comment by Daniel-J123** [comment]
![image](https://user-images.githubusercontent.com/66522801/98645313-bda3c980-236c-11eb-8251-fa6888f737a9.png)
 like this?
I know follow the code and there is data in  generated file `NS9_c.h5`, for example , I set the `checkpoint=50` and I simulate the demo 50 tstep, but When I next simulate, how do I use this checkpoint data to continue the calculation from step 51 instead of the first step??

**Comment by mikaem** [comment]
Look closer at the channel flow solver. Look at the initialization. There are two functions to do it, one called `init_from_file`.
