### ISSUE TITLE
sample_stats - no output

### ISSUE THREAD

**Issue by gsof1** [spectralDNS/spectralDNS#43]
Hi, Mikael,

I have been using your code in order to run a turbulent channel case similar to the KMM one. 
I am running in the command line something like:

python3 MKM.py --write_result 100 --checkpoint 100 --sample_stats 100 --optimization cython KMM

but there is no output of sampled data created. I obtain only two files of the extension .h5, where only the instantaneous velocity is  stored. Maybe i am doing something wrong!
Any help would be appreciated, thanks a lot!

**Comment by mikaem** [comment]
Hi,
Looks like there's no filename set in the demo for some reason??? Try with something like this [here](https://github.com/spectralDNS/spectralDNS/blob/564e779aa5061989c8a262b1117615a920bde810/demo/MKM.py#L303)

    solver.stats = Stats(context.U, solver.comm, filename='KMMstats')

**Comment by mikaem** [comment]
I may be wrong, but I think the only spectra implemented here is for the triply periodic isotropic. Would be great if you could add something:-)

**Comment by gsof1** [comment]
OK, i will keep the thread updated as soon as i have something!
