### ISSUE TITLE
solver.get_velocity(**context) with multiprocessing

### ISSUE THREAD

**Issue by ben-goldman** [spectralDNS/spectralDNS#52]
Hi Prof. Mortensen,

Really enjoying this project so far; it's really efficient and tightly fits our use case. 

I'm running into one particular roadblock. My goal is to compute the linear growth rate of a normal mode of a perturbation to Kelvin-Helmholtz instability. To do this, I want to sample the standard deviation of the velocity field at certain z-values at each time-step, by implementing something like the following in the `update(context)` function:
```
u0 = solver.get_velocity(**context)[0, :, N[1]//2] 
u1 = solver.get_velocity(**context)[1, :, N[1]//2] 
u0_std = np.std(u0)                   
u1_std = np.std(u1)                   
print(u1_std)                                 
amp[..., params.tstep - 1] = [u0_std, u1_std] 
```
where`solver` is a solver object created with `spectralDNS.get_solver(...)`, and  `amp` should be an array with shape `(2, T//dt)`.

This works fine when running the simulation on a single core. However, when I use multiprocessing, this is only able to access part of the full velocity field (as I'm sure you're aware). I.e., `u0` comes out to be a `(1, N[1]/Ncores)` array (where `Ncores` is the number of cpu cores allocated. When run in serial, `u0` is of shape `(1, N[1])`, which is the desired result. How would I approach fixing this, i.e. taking the standard deviation of the velocity field at each time step across the entire horizontal mesh? Due to disk space constraints, simply setting `write_result=1` and extracting the amplitude after the simulation finishes should be avoided, if possible. Could I allocate an array for each core? Is there a flag I can give to `get_velocity` to have it extract the entire field? Would somehow computing the amplitude in spectral space be advantageous? My humble apologies if these questions are unclear, or out-of-scope. Any advice you have would be greatly appreciated.

Thank you so much for creating this great tool and for your time. Please let me know if you desire clarification or have any concerns.

All the best,
Ben

**Comment by mikaem** [comment]
Hi Ben,

Glad to hear that you can find my code useful😃
The MPI always makes it a bit harder, but I have probably done what you're thinking about before. In this [link](https://github.com/spectralDNS/spectralDNS/blob/63987673e531cce35edba3493a23f6324e565e3f/demo/MKM.py#L177) I compute Reynolds stresses averaged over entire xy-planes with z being wall-normal direction. Is this what you want? Or something you can use?
